[package]
name = "rmus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
audiotags = "0.5"
cursive = "0.21"
cursive_table_view = "0.15"
dirs = "6.0.0"
lofty = "0.22.1"
rodio = { version = "0.20.1", features = ["symphonia-all"] }
